# Generated by Django 5.0.6 on 2026-04-09 21:35

import apps.records.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='attached_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.records.models.record_file_path),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='is_downloadable',
            field=models.BooleanField(default=False, help_text='If ticked, authorised users can download the attached file. Admin and the uploading doctor can always download regardless of this setting.', verbose_name='Allow file download'),
        ),
        migrations.AlterField(
            model_name='recordshare',
            name='purpose',
            field=models.CharField(blank=True, help_text='Reason for sharing', max_length=300),
        ),
        migrations.AlterField(
            model_name='recordshare',
            name='recipient_name',
            field=models.CharField(help_text='Receiving hospital or doctor name', max_length=200),
        ),
        migrations.AlterField(
            model_name='recordversion',
            name='change_note',
            field=models.CharField(blank=True, help_text='Brief description of what changed.', max_length=300),
        ),
    ]
