# Generated by Django 5.0.6 on 2026-04-09 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_alter_medicalrecord_attached_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='is_downloadable',
        ),
    ]
