# Generated by Django 5.0.6 on 2026-03-16 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('zoom', 'Zoom'), ('meet', 'Google Meet'), ('other', 'Other')], max_length=10)),
                ('link', models.URLField()),
                ('label', models.CharField(default='Default Room', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='consult_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consult Link',
                'verbose_name_plural': 'Consult Links',
            },
        ),
    ]
