# Generated by Django 5.0.6 on 2026-03-31 12:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_disabilities_patient_has_pending_fields_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['hospital_number'], name='idx_patient_hosp_num'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['last_name'], name='idx_patient_last_name'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['phone_number'], name='idx_patient_phone'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['is_active'], name='idx_patient_active'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['assigned_doctor'], name='idx_patient_doctor'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['created_at'], name='idx_patient_created'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['is_active', '-created_at'], name='idx_patient_active_date'),
        ),
    ]
