# Generated by Django 5.0.6 on 2026-03-16 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(help_text='e.g. 500mg, 5ml', max_length=100)),
                ('frequency', models.CharField(choices=[('once', 'Once Daily'), ('twice', 'Twice Daily'), ('thrice', 'Three Times Daily'), ('four', 'Four Times Daily'), ('weekly', 'Weekly'), ('as_needed', 'As Needed (PRN)')], max_length=20)),
                ('route', models.CharField(choices=[('oral', 'Oral'), ('iv', 'Intravenous'), ('im', 'Intramuscular'), ('topical', 'Topical'), ('inhaled', 'Inhaled'), ('sublingual', 'Sublingual')], default='oral', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('instructions', models.TextField(blank=True, help_text='Special instructions (take with food, etc.)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_schedules', to='patients.patient')),
                ('prescribed_by', models.ForeignKey(limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medication Schedule',
                'verbose_name_plural': 'Medication Schedules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicationDose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_datetime', models.DateTimeField(help_text='When this dose should be taken.')),
                ('taken', models.BooleanField(default=False)),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, help_text='Patient note when ticking.', max_length=200)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doses', to='medications.medicationschedule')),
            ],
            options={
                'verbose_name': 'Medication Dose',
                'verbose_name_plural': 'Medication Doses',
                'ordering': ['scheduled_datetime'],
            },
        ),
    ]
