# Generated by Django 5.0.6 on 2026-03-28 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=300)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('complete', 'Complete'), ('complete_with_errors', 'Complete — Some Rows Had Errors'), ('failed', 'Failed')], default='processing', max_length=30)),
                ('total_rows', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('skip_count', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Import Session',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField(help_text='Row number in the Excel file (row 1 = header)')),
                ('error_type', models.CharField(choices=[('missing_required', 'Missing Required Field'), ('invalid_format', 'Invalid Data Format'), ('duplicate', 'Duplicate Patient'), ('conflict', 'Conflict with Existing Record'), ('other', 'Other Error')], max_length=30)),
                ('field_name', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField()),
                ('raw_data', models.JSONField(default=dict, help_text='The original row data that failed, saved for manual correction')),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_import_errors', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='imports.importsession')),
            ],
            options={
                'verbose_name': 'Import Error',
                'ordering': ['row_number'],
            },
        ),
    ]
