# Generated by Django 5.0.6 on 2026-03-16 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', '🔐 Login'), ('LOGOUT', '🚪 Logout'), ('LOGIN_FAIL', '⚠️ Failed Login'), ('VIEW', '👁 View'), ('CREATE', '✅ Create'), ('UPDATE', '✏️ Update'), ('DELETE', '🗑 Delete'), ('DOWNLOAD', '⬇️ Download'), ('UPLOAD', '⬆️ Upload'), ('APPROVE', '✔️ Approve'), ('REVOKE', '✖️ Revoke'), ('TELECONSULT', '📹 Teleconsult')], max_length=20)),
                ('description', models.TextField(help_text='Human-readable description of the action.')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('url_path', models.CharField(blank=True, max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action. NULL if unauthenticated.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'default_permissions': ('view',),
            },
        ),
    ]
